BBOX:
  AREA_CONDITION: true
  MAX_AREA: 0.25
  MIN_AREA: 0.01
  MIN_IOU: 0.1
  MIN_OCCUR: 3
HEIGHT:
  HEIGHT: 720
  WIDTH: 1280
OPTICAL_FLOW:
  FLOW_TYPE: QUANTILE
  MIN_FLOW: 0.8
PATCH:
  ADDAVE: true
  RMVAVE: true
  patchH: 450
